/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: HampQuestCradle.html
Story format: Sugar
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Sugar;

public partial class @HampQuestCradle: Cradle.StoryFormats.Sugar.SugarStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------


	@HampQuestCradle()
	{
		this.StartPassage = "Dialouge Test";

		base.Vars = new VarDefs() { Story = this, StrictMode = false };


		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Dialouge Test

	void passage1_Init()
	{
		this.Passages[@"Dialouge Test"] = new StoryPassage(@"Dialouge Test", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text(@"''HampBot Test'' ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Hey there! ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Who are you?", @"Text Option 1", null);
		yield return text(@" ");
		yield return lineBreak();
		yield return link(@"Who am I?", @"Text Option 2", null);
		yield return text(@" ");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: Text Option 1

	void passage2_Init()
	{
		this.Passages[@"Text Option 1"] = new StoryPassage(@"Text Option 1", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text(@"''HampBot Test'' ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"I am a robot person.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Okay", @"Dialouge Test", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: Text Option 2

	void passage3_Init()
	{
		this.Passages[@"Text Option 2"] = new StoryPassage(@"Text Option 2", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text(@"''HampBot Test'' ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You are a robot person.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"#");
		yield return link(@"Okay", @"Dialouge Test", null);
		yield return text(@" ");
		yield return lineBreak();
		yield break;
	}


}